### ISSUE TITLE
Faster way to update?

### ISSUE THREAD

**Issue by ashwinreddy** [19RyanA/CheckPCR#2]
You might want to check out https://www.meteor.com/
It'll host your site (catch is, domain will be whateveryouwant.meteor.com)
It'll update everyone using the page when you push code back.

Even if you don't decide to use it,
is there a way to make it update without manually cloning the repo?

**Comment by 19RyanA** [comment]
I've been thinking of doing something like that for a while.
The only downside is that it would involve transferring people's passwords through code they can't see, which isn't very favorable. The advantage of using GitHub is that people can see the code they're downloading, so I'd prefer to keep running things this way.

The best solution would be to host this through Chrome's webstore, which will auto-update, but I'd prefer to use GitHub.

Maybe eventually in a future commit I might provide a choice to use it through a site like meteor or [Parse](https://www.parse.com/) (which I was originally thinking of), but for now, I'm probably going to stay with the chrome extension approach.

**Comment by 19RyanA** [comment]
The website's up, so this is resolved.
