### ISSUE TITLE
"List" feature not working

### ISSUE THREAD

**Issue by 19andrewc** [19RyanA/CheckPCR#4]
The list feature is not working for me, none of the assignments are showing up.

**Comment by 19RyanA** [comment]
First of all, are you seeing an illustration saying "No more assignments for today"?
If you are, then you may have marked all of your assignments that overlap today as done.

List view will only display the uncompleted assignments that span over the current day. If you want to view the uncompleted assignments to, you can click the check mark icon in the upper right corner in list view.

If that illustration isn't showing up, then there's a problem.

First of all, try refreshing.
If that doesn't solve the problem, then there's a bug.

**Comment by 19RyanA** [comment]
It turns out that it was a bug.

It's fixed now with the newest commit.
Thanks for alerting me.
