### ISSUE TITLE
Is not loading Assignments.

### ISSUE THREAD

**Issue by 22samb** [19RyanA/CheckPCR#7]
When I open Check PCR it opens and says "Loading your Assignments" and that message never goes away. Please help.
![untitled](https://cloud.githubusercontent.com/assets/16988299/12703254/95a6da3c-c7f3-11e5-82e3-3da727752f55.png)

**Comment by 19RyanA** [comment]
From what it looks like, something throws an error before the code has a chance to fetch assignments or update the "Last updated" text.

Try opening up the developer console (Inspect element then click the console tab) and paste what it says.
Also, when did you install Check PCR?

**Comment by 22samb** [comment]
I installed Check PCR about a month or 2 ago.

**Comment by 19RyanA** [comment]
Are you using the latest version, and what does the developer console say?

**Comment by 22samb** [comment]
I don't think I am using the latest version and the console says "Uncaught TypeError: Cannot read property '1' of null"

**Comment by 19RyanA** [comment]
Try updating to the latest version and see if that solves the problem.
If you still get the error, what is its line number?

**Comment by 22samb** [comment]
How do I update if i doesn't give me the option?

**Comment by 19RyanA** [comment]
Did you install it by using git or downloading the zip file?

**Comment by 22samb** [comment]
Downloaded using the zip.

**Comment by 19RyanA** [comment]
Then download the zip file again and copy everything inside of it into Check PCR's folder, replacing everything inside.

**Comment by 22samb** [comment]
Ok. Thanks.

**Comment by 19RyanA** [comment]
Does it work now?
